package tools.vitruv.change.testutils.metamodels

import multicontainment_b.Identified
import multicontainment_b.impl.Multicontainment_bFactoryImpl
import tools.vitruv.change.testutils.activeannotations.WithGeneratedRandomIds

@WithGeneratedRandomIds(identifierMetaclass=Identified)
class RandomIdMulticontainmentBFactory extends Multicontainment_bFactoryImpl {
}
