package tools.vitruv.change.testutils.metamodels

import attribute_to_structure_struct_1.Identified
import attribute_to_structure_struct_1.impl.Attribute_to_structure_struct_1FactoryImpl
import tools.vitruv.change.testutils.activeannotations.WithGeneratedRandomIds

@WithGeneratedRandomIds(identifierMetaclass=Identified)
class RandomIdAttributeToStructureStructFactory extends Attribute_to_structure_struct_1FactoryImpl {
}
